### ISSUE TITLE
Some msgs are not sent to the server until a followup msg is sent

### ISSUE THREAD

**Issue by davcomNZ** [LakeYS/Dishorde#110] opened 2021-05-23 20:17 UTC
Sometimes, a msg sent from the Discord channel will not appear ingame, until a 2nd or subsequent msg is sent (usually from the PC that issued the msg that has not yet appeared in-chat.)

Closest association we can make is that this seems to occur predominantly from the PC on which the chatbot is running when a msg is sent.

Other than that we have no idea what's causing this.

**Comment by LakeYS** [comment] 2021-06-11 18:22
Will do some testing soon. Are you able to post your exact config with sensitive information removed?

**Comment by davcomNZ** [comment] 2021-06-12 05:34
Hi Lake, you're after the serverconfig.xml ? or the chatbot config ?

**Comment by davcomNZ** [comment] 2021-06-12 05:39
FYI. Chatbot is running on a Linux PC (Ubuntu 20.04).

**Comment by LakeYS** [comment] 2021-06-12 19:04
The bot's config. The exact version of the game (via 7d!version) will also help

**Comment by davcomNZ** [comment] 2021-06-14 03:20
7DTD Discord chatbot Config.json
![Selection_034](https://user-images.githubusercontent.com/18519634/121834898-fa310c80-cd23-11eb-841d-f20db843f067.png)

[14:50] BOT 7DTD-ChatBot: Game version: Alpha 19.5 (b60) Compatibility Version: Alpha 19.5

**Comment by davcomNZ** [comment] 2021-06-14 03:41
FWIW, I have had a persistent Telnet error when a command was issued _through the providers TCAdmin_ which I contacted TCAdmin about since my provider was unable to provide a fix, which TCAdmin responded to by saying "the error is safe to ignore but this is fixed in TCAdmin 2.0.165.1".
I have no idea whether that issue has a bearing on the chatbot operation but as they both use Telnet felt it worth mentioning.
[20210527_Telnet_IOException_EVERY_time_a_command_is_issued_in_web_console.pdf](https://github.com/LakeYS/7DTD-Discord/files/6645475/20210527_Telnet_IOException_EVERY_time_a_command_is_issued_in_web_console.pdf)

**Comment by LakeYS** [comment] 2021-06-23 19:10
I have not yet been able to replicate your issue -- unfortunately, there have been a lot of reports of compatibility issues between 7DTD-Discord and other server utilities. The cause may be a conflict with TCAdmin.

I will be doing more testing soon to look into a fix for this. In the meantime, if you can catch the problem with the `log-telnet` option enabled, a console log of this may be helpful.

**Comment by davcomNZ** [comment] 2021-06-26 16:33
I have been using the log-telnet option since starting with 7DTD-Discord but there has been no obvious error message related to 7DTD-Discord in all that time. While I can see a direct correlation to the Telnet errors that do show when issuing a command via TCAdmin, nothing appears in the logs at all with respect to when messages don't get displayed ingame. There is 1 other admin in our Discord channel for the bot and he has advised me when messages appear in Discord but haven't yet appeared ingame via the bot ( I often use 7DTD-Discord bot to communicate with players when I'm not ingame myself). None of the messages are lost; the bot seems to store them and send them on when there's further messages queuing up behind so it looks like the bot does know about every message but for whatever reason isn't able to push them ingame straight away. We've had occasions when a single message may not have got through for literally hours if there was no following messages to force either the bot ? or the game ? to interact with the bots message queue.

**Comment by LakeYS** [comment] 2021-06-26 19:11
I see. From the sound of it, the messages are getting stuck in a buffer. The strange part of this is: 7DTD-Discord creates a buffer for messages from 7DTD->Discord, but *not* inverse from Discord->7DTD, which is where the problem appears to lie.

For best results, also make sure the bot is updated to the latest release (issued a few days ago) and the latest LTS version of Node.js -- some users experiencing similar issues have reported this fixing it. Ideally, we want to try to reproduce the problem on the latest release, with the latest version of Node.js installed on the system.

**Comment by davcomNZ** [comment] 2021-06-26 20:29
I did note that 1.7.3 has been released just prior to my last post. Is the update procedure as simple as copying away the config.json, wiping the folder contents and replacing with all of 1.7.3 then copy back the old config.json ? I'll check if a node.js update is available.

**Comment by LakeYS** [comment] 2021-06-26 21:06
Yes, should be simple as that.

**Comment by davcomNZ** [comment] 2021-06-26 21:28
Hmmm. Seems I have managed to bork things magnificently. Wiped all of my root 7DTD-Discord folder contents as intended but the sub-folder "node_modules" is no longer present in my bot root folder. Get back to you when I have some semblance of order :)
Node.js version is v6.14.13 (installed via Snap which advises no Node updates available)

**Comment by LakeYS** [comment] 2021-06-26 22:14
*Correction on before, you also need to re-run `npm install` after replacing files

**Comment by davcomNZ** [comment] 2021-06-27 00:58
Downloaded "v1.7.3" (7DTD-Discord.tar.gz) under Assets on Github, extracted to 7DTD-Discord folder after wiping all files/folders within, copied config.json back, ran npm install. Bot is up and connected to 7DTD server but still showing v1.7.2 running not v1.7.3.

**Comment by davcomNZ** [comment] 2021-06-27 00:59
There was a notice of a major NPM update, from v6.14.13 to v7.19.0, which has also been done but repeating the bot upgrade process still results in the console showing that it's v1.7.2 that's running.

**Comment by davcomNZ** [comment] 2021-06-27 01:15
Downloaded v1.7.3 from Github 3 times. First 2 installed against npm 6.14.13 and last against npm 7.19.0.
![Selection_036](https://user-images.githubusercontent.com/18519634/123529970-c2758c00-d749-11eb-910a-47b943c6a061.png)

**Comment by davcomNZ** [comment] 2021-06-28 18:47
A reboot fixed the issue with v1.7.3 not showing as running.

**Comment by LakeYS** [comment] 2021-06-28 21:26
For the release version number, you can now re-download to receive the correct version number. My apologies for the mix-up.

**Comment by davcomNZ** [comment] 2021-07-03 05:39
All good now thanks.
Was a little premature in saying a reboot fixed it because on further checking at the time no it hadn't but is now.

**Comment by LakeYS** [comment] 2021-07-05 21:08
Good to hear. Has the new update resolved the follow-up message problem?

**Comment by davcomNZ** [comment] 2021-07-13 13:43
Left it for a few days to see if the message problem was resolved but our server has gone incredibly quiet so not able to confirm at this time. Will post again if we do encounter it.

**Comment by LakeYS** [comment] 2021-12-10 23:57
Closing for now. Feel free to comment if further assistance is needed.

**Closed by LakeYS** 2021-12-10 23:57 UTC
